import 'element-plus/es/components/button/style/css'
import 'element-plus/es/components/row/style/css'
import 'element-plus/es/components/col/style/css'
import 'element-plus/es/components/form/style/css'
import 'element-plus/es/components/form-item/style/css'
import 'element-plus/es/components/input-number/style/css'
import 'element-plus/es/components/date-picker/style/css'
import 'element-plus/es/components/input/style/css'
import 'element-plus/es/components/select/style/css'
import 'element-plus/es/components/option/style/css'
import 'element-plus/es/components/checkbox/style/css'
import 'element-plus/es/components/radio/style/css'
import 'element-plus/es/components/rate/style/css'
import 'element-plus/es/components/cascader/style/css'
import 'element-plus/es/components/switch/style/css'
import 'element-plus/es/components/tree-select/style/css'
import 'element-plus/es/components/transfer/style/css'

// import 'element-plus/theme-chalk/dark/css-vars.css'
